import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import NavbarLandingPage from "./components/NavbarLandingPage";
import { getUserMeLoader } from "./lib/actions/validate-user";

const poppins = Poppins({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user =await getUserMeLoader()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <Providers user={user} >
          <div className="flex flex-col min-h-screen">
          <Toaster position="top-right"/>
          <NavbarLandingPage/>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
